# NumPy

### NumPy array

###### * They take less memory than lists. Eg an integer stoed in list  requires 28 bytes while in np array it requires 8 bytes.
###### * Time execution is faster in np arrays
###### * Easier to use.
###### * Functionality is better

##### Why is numpy faster?

###### This is because it uses vectorization which helps to perfoem mathematical operations on multiple elements at once rather than once by one.

# *******************************************************************************************

In [1]:
import numpy as np

In [2]:
# Lists can store values of different types.Eg a list can have int,float,strings at the same time, in the
# same list.

# Numpy arrays can only store values of one type at a time.

# If we have an some int values,and a string in a list, and then we make a np array
# from the list. Then all the values in the np array will automaticaaly be strings.

In [3]:
l = [1,2,"a","3",4]

a = np.array(l)

print(a)

['1' '2' 'a' '3' '4']


In [4]:
# We can however choose the type of value we want it to have.
# For this we need to pass in an argument named dtype.

# It is important to make sure that it is possible to convert a certain value to
# the specified dtype.
# Eg - we cannot cange "a" to integer in the above array. 

In [5]:
l = [1,2,"3",4]

a = np.array(l,dtype = int)

print(a)

[1 2 3 4]


In [6]:
#Copying multiple times
b = np.array(l*3)

print(b)

['1' '2' '3' '4' '1' '2' '3' '4' '1' '2' '3' '4']


##### Some function to create standard np arrays

##### zeroes

In [7]:
# We need to provide the size. i.e Number of zeroes.
# By default all values will be float.
# We can change the dtype

In [8]:
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [9]:
a = np.zeros(3,dtype = int)
print(a)

[0 0 0]


In [10]:
# 2-D 
# np.zeroes((m,n),dtype)

In [11]:
a = np.zeros((3,3),dtype = int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


##### ones

In [12]:
# We need to provide the size. i.e Number of zeroes.
# By default all values will be float.
# We can change the dtype

In [13]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [14]:
a = np.ones(3,dtype = int)
print(a)

[1 1 1]


In [15]:
# 2-D 
# np.ones((m,n),dtype)

In [16]:
a = np.ones((3,3),dtype = int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


##### full

In [17]:
# Using this we can create np arrays with number/value of our choice.

# By default values are int.

# a = np.full(size,value,dtype)

# 2-D
# a = np.full((m,n),value,dtype)

In [18]:
a = np.full(3,2)
print(a)

[2 2 2]


In [19]:
a = np.full(3,2,dtype = float)
print(a)

[2. 2. 2.]


In [20]:
a = np.full((3,3),2)
print(a)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


##### empty

In [21]:
# Returns a new array of given shape and type, without initializing entries.i.e garbage values4

# The values are random even if there is some pattern.

In [22]:
a = np.empty(9,dtype = int)
print(a)

[         1          0          1          0          0          0
          0          0 -715838576]


In [23]:
a = np.empty((4,4),dtype = int)
print(a)

[[   0    0    0    0]
 [   0    0    0    0]
 [   0    0 1280    0]
 [   0    0    0    0]]


##### arange

In [24]:
# When we want a progression.i.e. when we have a start,stop and step.

# By deault start is 0 if we do not give start and stop both.
# One argument means we have given stop value.

# start is inclusive stop is exlusive.

In [25]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
a = np.arange(3,10)
print(a)

[3 4 5 6 7 8 9]


In [27]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


##### linspace

In [28]:
# It is used to generate samples/values between start and stop.
# We dont give it a step. We give the number of values we want betweem start and stop.
# Step is chosen automatically to fit the values between start and stop .

# If we do not give the no. of values default is 50.

# start and stop both are included. If we do not want stop value,we can use the 
# argument endpoint which is a boolean True by default.4

# It is neccesary to give atleast two args.

# np.linspace(start,stop,endpoint,num_of_vals,dtype)

# The difference between consecutive values may not be common. Its random

In [29]:
a = np.linspace(10,20)
print(a)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [30]:
a = np.linspace(10,20,10)
print(a)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [31]:
a = np.linspace(10,20,10,dtype = int)
print(a)

[10 11 12 13 14 15 16 17 18 20]


In [32]:
a = np.linspace(10,20,10,endpoint = False,dtype = int)
print(a)

[10 11 12 13 14 15 16 17 18 19]


##### identity

In [33]:
# Used to make identity matrix.

# IMPORTANT - We can only make an argument of the order N*N with this.

# np.identity(n)

In [34]:
a = np.identity(3,dtype = int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


##### eye

In [35]:
# Used to make identity matrix.

# IMPORTANT - We can make N*M matrices too.

# np.identity(n)

In [36]:
a = np.eye(3,dtype = int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [37]:
a = np.eye(3,4,dtype = int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


##### random.rand()

In [38]:
# Used to generate given number of random value between 0 and 1.
# If we want a different range we can multiply the above result accordingly.

In [39]:
#Gives one random value.
a = np.random.rand()
print(a)

0.06950728929715555


In [40]:
a = np.random.rand(3)
print(a)

[0.50585292 0.83749278 0.97475277]


In [41]:
# In range o to 10
a = np.random.rand(5)*10
print(a)

[6.39082658 7.40032378 5.94955012 3.83823356 0.98804793]


In [42]:
# 2-D matrix.
a = np.random.rand(3,4)
print(a)

[[0.90709857 0.38680461 0.41128849 0.3596971 ]
 [0.14822118 0.28347082 0.92803058 0.49360835]
 [0.59799679 0.16748594 0.10255955 0.26256199]]


##### random.randint()

In [43]:
# It gives use a random integer between 0 and number specified.
# We can choose the number of values we want by giving size arg.

In [44]:
a = np.random.randint(5)
print(a)

1


In [45]:
a = np.random.randint(5,size = 10)   #This means 10 values between 0 and 5,5 not included.
print(a)

[1 0 0 2 0 2 0 0 1 0]


In [46]:
a = np.random.randint(10,size = (2,3))
print(a)

[[9 2 1]
 [8 7 9]]


In [47]:
#If we do not specify second arg as size. This means we have given start and stop.
# stop has to be greater than start.
print(np.random.randint(4, 10))

6


##### reshape

In [48]:
# Consider we have a 1-D list/numpy array and we want to make a 2-D list out of it.
# For that we can use the reshape function.

In [49]:
a = [1,2,3,4,5,6,7,8,9]
a_np = np.array(a)

In [50]:
a_2d = a_np.reshape(3,3)
print(a_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
# It is necessary to ensure it is possible to reshape the list.

# IMPORTANT

# Read more about the reshape function.

##### Some functions for Properties of nump arrays

In [52]:
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)

[1 2 3 4 5]
int32


In [53]:
# .data - gives the address of first element in array

# .dtype - gives the datatype of elements

# .shape - gives the shape(order) of array. (M,) for 1-D arrays and (M,N) for 2-D arrays.

# .strides - gives the no. of bytes me need to move to get to next element.(For 2-D arrays
#            we get (x,y) where x is no of bytes to move to next row and y is no of bytes
#            needed to move to next column.)

In [54]:
print(a.data)
print(a.dtype)
print(a.shape)
print(a.strides)

int32
(5,)
(4,)


In [55]:
l = [[1,2,3],
     [4,5,6],
     [7,8,9]]
a = np.array(l)

In [56]:
print(a.data)
print(a.dtype)
print(a.shape)
print(a.strides)

int32
(3, 3)
(12, 4)


##### Accessing elements

In [57]:
# Indixing and slicing are the same as lists for 1-D lists.
l = [1,2,3,4,5]
a = np.array([1,2,3,4,5])

print(l[2])
print(a[2])

print(l[2:])
print(a[2:])

3
3
[3, 4, 5]
[3 4 5]


In [58]:
# 2-D 

In [59]:
l = [[1,2,3],
     [4,5,6],
     [7,8,9]]
a = np.array(l)

print(l[2][1])
print(a[2][1])

8
8


In [60]:
#IMPORTANT
# Another way of doing the same with numpy arrays is:-
print(a[2,1])

8


In [61]:
# For 2-D list everything that works with lists works with numpy arrays.
# But numpy arrays have an added advantage.

l = [[1, 2,  3, 4],
     [5, 6,  7, 8],
     [9, 10, 11,12],
     [13,14, 15,16]]
a = np.array(l)

In [62]:
# Consider we have to print the elements 4,8,12.
# We can slice rows 0 to 2 and have the 3rd column.

# print(l[0:3][2]) would give the result 9,10,11,12 with lists.

# This is because in lists we can have constant row and changing columns but
# we cannot have constant column and changing rows with just slicing.
# We need to loop through each row and print the required column.

# The reqson for that is l[0:3][2] in steps is:
# l[0:3] which is tows 0,1,2 so we get a list of lists with these three rows.
# l[0:3] =   [[1, 2,  3, 4],
#                 [5, 6,  7, 8],
#                 [9, 10, 11,12]]

# Now l[0:3][2] means the second part of l[0:3] which is [9, 10, 11,12].

# But our aim was to get 4,8,12.

# To do that with lists we need to loop through each row and print the req column.

# Not only this if we used this we may end up getting errors in some cases like :-
# l[0:3][3] since now l[0:3] has only 3 elements(lists inside) and we want to access one on index 4.
# So its wise to use numpy arrays in such cases. 

In [63]:
# With numpy arrays we have an advantage of using this syntax
# print(a[m,n])

print(a[0:3,2])

print(a[0:3,3])

[ 3  7 11]
[ 4  8 12]


In [64]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

for i in input_[2,0:3]:
    print(i,end = " ")

print()
for i in input_[1:,3]:
    print(i,end= " ")

print()

for i in input_[2:,:]:
    for j in i:
        print(j,end = " ")

print()

for i in input_[1:3,1:3]:
    for j in i:
        print(j,end = " ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

##### Mathematical operations

In [65]:
# To do any mathematical operations on lists we need to loop through the elements
# and we need to perform those operations on each element.

# In numpy arrays this can be easily done and more efficiently.

In [66]:
import numpy as np
l = [1,2,3,4,5]
a = np.array([1,2,3,4,5])

# Adding 1 to each element of the list and array.

# List
l = [i+1 for i in l]
print(l)

# Numpy array
a = a+1
print(a)

[2, 3, 4, 5, 6]
[2 3 4 5 6]


In [67]:
# Similarly for mathematical operations with different arrays.
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = a + b
print(c)

[ 7  9 11 13 15]


In [68]:
c = a - b
print(c)

c = a * b
print(c)

c = a / b
print(c)

c = a // b
print(c)

c = a**b
print(c)

c = a % b
print(c)

[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[      1     128    6561  262144 9765625]
[1 2 3 4 5]


In [69]:
# Some logical operations
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [70]:
a>b

array([False, False, False, False, False])

In [71]:
a<b

array([ True,  True,  True,  True,  True])

In [72]:
a == b

array([False, False, False, False, False])

In [73]:
# Each nonzero value represents true
np.logical_and(a,b)

array([ True,  True,  True,  True,  True])

In [74]:
# Each nonzero value represents true
np.logical_or(a,b)

array([ True,  True,  True,  True,  True])

##### Some mathematical functions for np array

In [75]:
a = np.array([1,2,3,4,5])

In [76]:
a.sum()

15

In [77]:
a.mean()

3.0

In [78]:
a.min()

1

In [79]:
a.max()

5

In [80]:
#To get the index of min and max we use argmin and argmax functions.

In [81]:
a.argmin()

0

In [82]:
a.argmax()

4

In [83]:
np.logical_not(a)

array([False, False, False, False, False])

##### Boolean indexing.

In [84]:
l = [True,True,False,False,True]
a = np.array([1,2,3,4,5])

print(a[l])

[1 2 5]


In [85]:
# The places where we had True are displayed.

IMPORTANT

Q.) Print all the elemnets greater than 10 from the given list.
l = [12,13,9,8,15,17,1]

In [86]:
l = [12,13,9,8,15,17,1]
a = np.array(l)

print(a[a>10])

[12 13 15 17]


Q.)Print all elements greater than 10 and less than 15

In [87]:
l = [12,13,9,8,15,17,1]
a = np.array(l)

print(a[(a>10) & (a<15)])

[12 13]


##### Updating multiple values at once

In [88]:
l = [12,13,9,8,15,17,1]
a = np.array(l)

a[:3] = 100

print(a)

[100 100 100   8  15  17   1]


In [89]:
l = [12,13,9,8,15,17,1]
a = np.array(l)

a[a>10] = 50

print(a)

[50 50  9  8 50 50  1]


##### where function

In [90]:
l = [12,13,9,8,15,17,1]
a = np.array(l)

# We can get the index using the where function, even if there are multiple indices.

index = np.where(a == 13)
print(index)

(array([1], dtype=int64),)


In [91]:
index  = np.where(a>10)
print(index)

(array([0, 1, 4, 5], dtype=int64),)


In [92]:
# Since np.where function returns a tuple, to get the elements of the list having indices we need to takes 
# the first element of the tuple which has the list of indices.
for i in index[0]:
        print(i,end = " ")

0 1 4 5 

In [93]:
# We can get multiple answers with multiple indices at once.
index  = np.where(a>10)
print(a[index])

[12 13 15 17]


### Numpy Broadcasting

Mathematical operation that weve seen so far only were performed between arrays of
same size/order.

If the order is not the same element wise operations may result in errors.

Thus we use broadcasting.

Consider 2-D arrays.

if the order is m*n and p*q then mathematical operations between the two cannot
be performed unless one of p or q is 1.
eg [[1,2,4], and [1,4,5]
    [4,5,6],
    [7,8,9]]

We can peroform mathematical operations on this as numpy reads this as 
eg [[1,2,4], and [[1,4,5],
    [4,5,6],      [1,4,5],
    [7,8,9]]      [1,4,5]]
    
if in both arrays one of the dimensions is 1 the both arrays are broadcasted.

Another way is using transpose
eg m*n and n*m arrays.Here we can use the teanspose of one.

In [94]:
# Some functions:-

##### resize

In [97]:
# It can be used in two ways:-

# 1.) When m x n = p x q ie the product is the same.

a = np.array([1,2,3,4,5,6])
# order is 1*6 . product is 6.
print(a)

print()

a.resize(2,3)
# order is 2*3 . product is 6.
print(a)


[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [98]:
# 2.) When the product of order is not the same.
#     In this 0s are appended for blank spaces.

a = np.array([1,2,3,4,5,6])
# order is 1*6 . product is 6.
print(a)

print()

a.resize(3,4)
# order is 3*4 . product is 12.
print(a)


[1 2 3 4 5 6]

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


##### reshape

In [101]:
a = np.arange(8)
print(a)

print()

print(a.reshape(4,2))

print()

print(a.reshape(2,4))

print()

# 3-D
print(a.reshape(2,2,2))

[0 1 2 3 4 5 6 7]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1 2 3]
 [4 5 6 7]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
