Q1.)NumPy 2D array

In [1]:
import numpy as np

l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(l)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q2.)NumPy 0s and 1s

In [2]:
import numpy as np

a = np.zeros(10,dtype = int)

a[4] = 1

for i in a :
    print(i,end=" ")

0 0 0 0 1 0 0 0 0 0 

Q3.)NumPy Inclusive

In [4]:
import numpy as np
a = np.arange(9,50,1)
for i in a:
    print(i,end = " ")

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

Q4.)Identity Matrix

In [5]:
import numpy as np
a = np.eye(5,6,dtype = int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


Q5.)Cut the Rope

In [6]:
import numpy as np
a = np.linspace(0,5,10)
for i in a:
    if i !=0 and i!=5:
        print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [8]:
#Alternate soln
import numpy as np
start = 0
end = 5
no_of_points = 10

a = np.linspace(start,end,no_of_points)[1:9]

for i in a:
    print(format(i,'.2f'))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


Q6.)Print Elements

In [9]:
# This soln takes more space less time.

import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

ans1 = np.array(input_[2,0:3])
ans2 = np.array(input_[1:,3])
ans3 = np.array(input_[2:,:])
ans4 = np.array(input_[1:3,1:3])

for i in ans1:
    print(i,end = " ")

print()
for i in ans2:
    print(i,end= " ")

print()

for i in ans3:
    for j in i:
        print(j,end = " ")

print()

for i in ans4:
    for j in i:
        print(j,end = " ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

In [10]:
# Alternate solution
# This soln takes more time less space.

## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

for i in input_[2,0:3]:
    print(i,end = " ")

print()
for i in input_[1:,3]:
    print(i,end= " ")

print()

for i in input_[2:,:]:
    for j in i:
        print(j,end = " ")

print()

for i in input_[1:3,1:3]:
    for j in i:
        print(j,end = " ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

Q7.)Non-Zero elements

In [27]:
import numpy as np
l = np.array([1,2,0,0,4,0])
for i in np.where(l>0)[0]:
    print(i,end = " ")


0 1 4 

Q8.)Multiples of 3

In [30]:
import numpy as np
a = np.arange(1,20,2)

for i in np.where(a%3 == 0)[0]:
    print(i,end = " ")

1 4 7 

Q9.)Odd elements

In [34]:
import numpy as np
a = np.arange(1,11,1)

indices = np.where(a%2 != 0)

a[indices] = -1

for i in a:
    print(i,end = " ")

-1 2 -1 4 -1 6 -1 8 -1 10 

Q10.)Replace Max

In [40]:
import numpy as np

a = np.array([11, 2, 13,4, 15, 6, 27, 8, 19])

a[a.argmax()] = 0

for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


Q11.)Negate Elements

In [56]:
import numpy as np

a = np.arange(1,11,1)

for i in range(2,8):
    a[i] = -a[i]
for i in a:
    print(i)
 

1
2
-3
-4
-5
-6
-7
-8
9
10


In [63]:
#Alternate soln.
import numpy as np

a = np.arange(1,11,1)

indices = np.where((a>=3) & (a<=8))
    
for i in indices:
    a[i] = np.negative(a[indices])

for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


Q12.)Height

In [65]:
import numpy as np

age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

indices = np.where(height>155)[0]

for i in indices:
    print(age[i],height[i],end = " ")
    print()
    

15 156 
19 180 
20 162 
21 157 
22 158 
23 179 
16 182 
18 183 
20 159 
15 160 
17 172 


Q13.)Sort by column - to be solved

In [94]:
import numpy as np

l =[[21 ,20 ,19 ,18, 17],
   [16, 15, 14, 13, 12],
   [11, 10 , 9,  8,  7],
   [ 6 , 5  ,4  ,3  ,2]]

a = np.array(l)

a = sorted(a,key = lambda item:item[0])
a = np.array(a)
print(a)


[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


Q14.)Killed in USA

In [31]:
import numpy as np
import csv

with open('Dataset/terrorismData.csv',encoding = "ISO-8859-1") as file_obj:
    file_data = csv.DictReader(file_obj,skipinitialspace = True)
    
    killed = []
    
    for row in file_data:
        if row["Country"] == "United States":
                killed.append(row["Killed"])
    
    np_killed = np.array(killed)
    
    np_killed[np_killed == ""] = 0
    
    np_killed = np.array(np_killed,dtype = float)
    
    for i in np_killed:
        print(int(i))
    

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


Q15.)Total Killed in USA

In [33]:
with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)
    
    killed = []
    
    for row in data :
        if row["Country"] == "United States":
            killed.append(row["Killed"])
        
    npKilled = np.array(killed)
    
    npKilled[npKilled == ""] = "0.0"
    
    npKilled = np.array(npKilled,dtype = float)
    
    print(int(npKilled.sum()))

3771


Q16.)Terrorism Day

In [34]:
with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)
    
    attacks = 0
    
    for row in data:
        if int(row["Day"])>=10 and int(row["Day"])<=20:
            attacks+=1
            
    print(attacks)

66330


Q17.)Terrorism Date

In [60]:
with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)
    
    attacks = 0
    
    for row in data:
        if row["Year"] == "2010" and row["Month"] == "1" and (row['Day']!= '0' ) :
            attacks+=1
            
    print(attacks)

271


In [61]:
# Alternate solution.
with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)
    
    date = []
    
    for row in data:
        date.append([row['Day'],row['Month'],row['Year']])
        
    npDate = np.array(date,dtype = int)
    
    npDate = npDate[npDate[:,2] == 2010]
    npDate = npDate[npDate[:,1] == 1]
    npDate = npDate[npDate[:,0] != 0]
    
    print(npDate.shape[0])

271


Q18.)Terror Casualty Attack

In [130]:
import numpy as np
import csv

with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)

    info = []
    
    for row in data:
        if row['State'] == "Jammu and Kashmir" and row['Year'] == "1999" :
            info.append([row["City"],row["Month"],row["Killed"],row["Wounded"],row["Group"]])

    npInfo = np.array(info)
    
    npInfo = npInfo[np.logical_or(np.logical_or(npInfo[:,1] == "5" ,npInfo[:,1] == "6"),npInfo[:,1] == "7")]
    
#     npInfo[np.where(npInfo[:] == "")] = '0'
# or
# without using where.
    npInfo[npInfo == ""] = '0'
    
    killed = np.array(npInfo[:,2],dtype = float)
    wounded = np.array(npInfo[:,3],dtype = float) 
    cas = killed + wounded
    
    max_index = cas.argmax()
    
    print(int(cas[max_index]),npInfo[max_index,0],npInfo[max_index,4],end = " ")


22 Kargil District Separatists 

Q19.)Terror Casualty Red

In [134]:
import numpy as np
import csv

with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)

    info = []
    
    for row in data:
        if row['State'] == "Jharkhand" or row['State'] == "Odisha" or row['State'] == "Andhra Pradesh" or row['State'] == "Chhattisgarh":
            info.append([row["Killed"],row["Wounded"]])

    npInfo = np.array(info)

    npInfo[npInfo == ""] = '0'
    
    cas = np.array(npInfo,dtype = float)
    
    casualities = np.sum(cas,axis = 1)
    casualities = np.sum(casualities)

    print(int(casualities))

5628


Q20.)Terror City Casualty

In [72]:
import numpy as np
import csv

with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)

    info = []
    
    for row in data:
        if row['Country'] == "India":
            info.append([row["City"],row["Killed"],row["Wounded"]])

    npInfo = np.array(info)

    npInfo[npInfo == ""] = '0'
    
    killed = np.array(npInfo[:,1],dtype = float)
    wounded = np.array(npInfo[:,2],dtype = float) 
    cas = killed + wounded
    cas = cas.reshape(len(npInfo),1)

    npInfo = np.append(npInfo,cas,axis = 1)
    
    d = {}
    
    for i in npInfo:
        
        if i[0] == "Unknown":
            continue
            
        if i[0] in d:
            d[i[0]] += int(float(i[3]))
        else:
            d[i[0]] = int(float(i[3]))
            
    l = sorted(d,key = lambda item:d[item],reverse = True)
    
    for i in l[:5]:
        print(i,d[i],end = " ")
        print()

Srinagar 3134 
New Delhi 2095 
Mumbai 2016 
Jammu 1119 
Guwahati 822 


In [74]:
import numpy as np
import csv

with open("Dataset/terrorismData.csv",encoding = "ISO-8859-1") as file_obj:
    data = csv.DictReader(file_obj)

    info = []
    
    for row in data:
            info.append(row["Day"])

    npInfo = np.array(info)

    npInfo[npInfo == ""] = '0'
    
    
    d = {}
    
    for i in npInfo:
        if i in d:
            d[i]+=1
        else:
            d[i] = 1
    
    m = max(d, key=d.get) 
    
    print(m,d[m],end = " ")

15 6500 